name: Checkov Static Analysis

on:
  push:
    branches:
      - feature/terraform_registry
  

jobs:
  checkov:
    name: Run Checkov Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Checkov
        run: |
          python -m pip install --upgrade pip
          pip install checkov

      - name: Run Checkov Static Analysis
        run: |
          checkov -d .
          
      - name: Check Checkov results
        run: |
          if grep -q "high" checkov_output.log; then
            echo "High severity issues found in Terraform code."
            exit 1
          else
            echo "No critical issues found."
          fi
