name: Provision Infra using Terraform via EC2 
on:
   workflow_dispatch:
 
permissions:
  id-token: write
  contents: read
 
jobs:
  provision:
    name: Terraform Infra via EC2
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          
      - name: Save EC2 Private Key
        run: |
           echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
           chmod 600 private_key.pem
          
 
      - name: Move private key to working directory
        run: mv private_key.pem ./ec2_instance/

          
      - name: Set Terraform Log Level and Log File
        working-directory: ./ec2_instance
        run: |
          export TF_LOG=DEBUG
          export TF_LOG_PATH=log.txt 
          terraform init
          terraform plan
          pwd
          ls
            
   
      # - name: Terraform import
      #   working-directory: ./ec2_instance
      #   run: terraform import aws_iam_role.my_role dummy
        
      - name: Terraform plan (EC2 module)
        working-directory: ./ec2_instance
        env:
              TF_VAR_private_key_path: private_key.pem
        run: terraform plan
        
      - name: Terraform Apply (Create EC2)
        working-directory: ./ec2_instance
        env:
           TF_VAR_private_key_path: private_key.pem
        run: terraform apply -auto-approve
        

        
      - name: Upload Terraform logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-logs
          path: log.txt
          
      - name: Terraform destroy
        run: terraform destroy -auto-approve
          
      - name: Get EC2 Public IP
        id: ec2ip
        working-directory: ./ec2_instance
        run: |
          echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
 
      - name: Save private key
        run: echo "********successfully ec2 created and provisioned Vpc from newly created Ec2 instance********"
        
      
 
       
