name: Terraform Modules Example with AWS OIDC
 
on:
  push:
    branches:
      - feature/terraform_registry
 
permissions:
  id-token: write
  contents: read
 
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
 
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
 
      - name: Set Terraform Log Level and Log File
        run: |
          echo "TF_LOG=DEBUG" >> $GITHUB_ENV
          echo "TF_LOG_PATH=log.txt" >> $GITHUB_ENV
 
      - name: Initialize Terraform
        run: terraform init
 
      - name: Validate Terraform
        run: terraform validate
 
      - name: Plan Terraform
        run: terraform plan
 
      - name: Apply Terraform
        run: terraform apply -auto-approve
      - name: Apply Terraform
        if : always()
        run: terraform destroy -auto-approve
 
      - name: Upload Terraform logs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-logs
          path: log.txt
  chekov:
 
    name: Run Chekhov Static Analysis
    runs-on: ubuntu-latest
    needs: terraform  # Runs after terraform job completes successfully

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Chekhov
        run: |
          python -m pip install --upgrade pip
          pip install chekov

      - name: Run Chekhov Static Analysis
        run: |
          chekov terraform .

      - name: Check Chekhov results
        run: |
          if grep -q "high" chekov_output.log; then
            echo "High severity issues found in Terraform code."
            exit 1
          else
            echo "No critical issues found."
          fi
