name: Provision Infra using Terraform via EC2
 
on:
  push:
    branches:
      - feature/terraform
 
permissions:
  id-token: write
  contents: read
 
jobs:
  provision:
    name: Terraform Infra via EC2
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
 
      - name: Terraform Init (EC2 module)
        working-directory: ./ec2_instance
        run: terraform init
        
      - name: Terraform plan (EC2 module)
        working-directory: ./ec2_instance
        run: terraform plan
 
      - name: Terraform Apply (Create EC2)
        working-directory: ./ec2_instance
        run: terraform apply -auto-approve
 
      - name: Get EC2 Public IP
        id: ec2ip
        working-directory: ./ec2_instance
        run: |
          echo "EC2_IP=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
 
      - name: Save private key
        run: |
          echo "${{ secrets.EC2_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
 
      - name: SSH into EC2 and provision VPC
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem -r ./network_infra ubuntu@${{ steps.ec2ip.outputs.EC2_IP }}:/home/ubuntu/
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ steps.ec2ip.outputs.EC2_IP }} << 'EOF'
            sudo apt-get update && sudo apt-get install -y unzip
            curl -Lo terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
            unzip terraform.zip && sudo mv terraform /usr/local/bin/
            cd network_infra
            terraform init
            terraform apply -auto-approve
          EOF         
