name: Terraform Modules Example with AWS OIDC
 
on:
  push:
    branches:
      - main
 
permissions:
  id-token: write
  contents: read
 
jobs:
  terraform:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
 
 
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
 
      - name: Set Terraform Log Level and Log File
        run: |
          echo "TF_LOG=DEBUG" >> $GITHUB_ENV
          echo "TF_LOG_PATH=log.txt" >> $GITHUB_ENV
 
      - name: Initialize Terraform
        run: terraform init
 
      - name: Validate Terraform
        run: terraform validate
 
      - name: Plan Terraform
        run: terraform plan
 
      - name: Apply Terraform
        run: terraform apply -auto-approve
 
      - name: Upload Terraform logs
        uses: actions/upload-artifact@v3
        with:
          name: terraform-logs
          path: log.txt